# 开发环境
server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql:///sleeve?serverTimezone=UTC
    username: root
    password: 826427
  # 配置jpa 打印sql到控制台
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

sleeve:
  # token配置
  security:
    # token加密字符串 盐
    jwtKey: maomao^_^-_-fanfan
    # 过期时间 s
    tokenExpiredIn: 8640000